name: Github Actions Build
on: [push, pull_request]
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        nim: [ '1.6.0', 'stable']

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    - name: Setup Nim
      uses: jiro4989/setup-nim-action@v1
      with:
        nim-version: ${{ matrix.nim }}
    
    - run: nimble test -y
    - run: nimble test --gc:orc -y
